// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace SubviewTest.Views
{
	public partial class ContainerView : NSView
	{
		public ContainerView (IntPtr handle) : base (handle)
		{
		}
	}
}
