// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace SubviewTest.Controllers
{
	public partial class ContainerViewController : NSViewController
	{
		public ContainerViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
