// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using AppKit;

namespace SubviewTest.Controllers
{
	public partial class MainWindowController : NSWindowController
	{
		public MainWindowController (IntPtr handle) : base (handle)
		{
		}

        public override void WindowDidLoad()
        {
            base.WindowDidLoad();
            Window.MovableByWindowBackground = true;
        }
    }
}
